<script setup lang="ts">
import { useForm } from '@inertiajs/vue3';
import ConfigurationLayout from '../../Layouts/ConfigurationLayout.vue';
import PageHeader from '../../Components/PageHeader.vue';

const props = defineProps<{ user: { id: number; name: string; is_active: boolean }; profiles: any[]; events: any[] }>();
const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Tegucigalpa' }).format(new Date());
const form = useForm({ monthly_salary: '', effective_from: today, effective_to: '', contract_start_date: today, contract_end_date: '', is_indefinite: true, default_payment_method: 'transfer', auto_generate_payroll_expense: false, notes: '' });
const submit = () => form.post(`/configuration/users/${props.user.id}/compensation`);
const money = (value: string) => new Intl.NumberFormat('es-HN', { style: 'currency', currency: 'HNL' }).format(Number(value));
const installment = (salary: string, first: boolean) => { const cents = Math.round(Number(salary) * 100); return money(((first ? Math.floor(cents / 2) : cents - Math.floor(cents / 2)) / 100).toFixed(2)); };
const date = (value?: string | null) => value ? new Intl.DateTimeFormat('es-HN', { dateStyle: 'long', timeZone: 'America/Tegucigalpa' }).format(new Date(`${value}T12:00:00-06:00`)) : 'Indefinido';
</script>
<template>
    <ConfigurationLayout>
        <PageHeader :title="`Compensación: ${user.name}`" description="Cada cambio crea un perfil histórico; no sobrescribe salarios anteriores." />
        <VAlert v-if="!user.is_active" type="warning" class="mb-4">El usuario está inactivo y no puede recibir una configuración nueva.</VAlert>
        <VCard class="surface-card mb-6"><VCardText class="pa-5"><VForm @submit.prevent="submit"><VRow><VCol cols="12" sm="6"><VTextField v-model="form.monthly_salary" label="Salario mensual" prefix="L" inputmode="decimal" :error-messages="form.errors.monthly_salary" /></VCol><VCol cols="12" sm="6"><VTextField v-model="form.effective_from" type="date" label="Vigencia del salario" :error-messages="form.errors.effective_from" /></VCol><VCol cols="12" sm="6"><VTextField v-model="form.contract_start_date" type="date" label="Inicio del contrato" :error-messages="form.errors.contract_start_date" /></VCol><VCol cols="12"><VSwitch v-model="form.is_indefinite" label="Contrato indefinido" color="primary" /></VCol><VCol v-if="!form.is_indefinite" cols="12" sm="6"><VTextField v-model="form.contract_end_date" type="date" label="Fin del contrato" :error-messages="form.errors.contract_end_date" /></VCol><VCol cols="12" sm="6"><VTextField model-value="15" label="Primer día de pago" readonly /></VCol><VCol cols="12" sm="6"><VTextField model-value="Último día del mes" label="Segundo pago" readonly /></VCol><VCol cols="12" sm="6"><VSelect v-model="form.default_payment_method" label="Método habitual" :items="[{ title: 'Efectivo', value: 'cash' }, { title: 'Tarjeta', value: 'card' }, { title: 'Transferencia', value: 'transfer' }]" :error-messages="form.errors.default_payment_method" /></VCol><VCol cols="12"><VSwitch v-model="form.auto_generate_payroll_expense" label="Generar gasto de nómina automáticamente" color="primary" /></VCol><VCol cols="12"><VTextarea v-model="form.notes" label="Notas" :error-messages="form.errors.notes" /></VCol></VRow><VAlert v-if="form.monthly_salary" type="info" variant="tonal" class="mb-4">Primera quincena: {{ installment(form.monthly_salary, true) }}. Segunda quincena: {{ installment(form.monthly_salary, false) }}.</VAlert><VBtn type="submit" color="primary" :disabled="!user.is_active" :loading="form.processing">Guardar perfil</VBtn></VForm></VCardText></VCard>
        <VCard class="surface-card"><VCardTitle>Historial</VCardTitle><VDataTable :headers="[{ title: 'Vigente desde', key: 'effective_from' }, { title: 'Hasta', key: 'effective_to' }, { title: 'Contrato', key: 'contract' }, { title: 'Salario', key: 'monthly_salary' }]" :items="profiles" hide-default-footer><template #item.effective_from="{ item }">{{ date(item.effective_from) }}</template><template #item.effective_to="{ item }">{{ date(item.effective_to) }}</template><template #item.contract="{ item }">{{ date(item.contract_start_date) }} → {{ date(item.contract_end_date) }}</template><template #item.monthly_salary="{ item }">{{ money(item.monthly_salary) }}</template></VDataTable></VCard>
        <VList v-if="events.length" class="mt-4 rounded-xl"><VListItem v-for="event in events" :key="`${event.occurred_at}-${event.text}`" :title="event.text" :subtitle="[event.performed_by, event.occurred_at].filter(Boolean).join(' · ')" /></VList>
    </ConfigurationLayout>
</template>
